cat("Welcome to this project.\n")
require(mapview)
require(sf)
require(devtools)
require(dplyr)
require(doParallel)
require(shadow)
require(landtools)
require(maptools)
require(leaflet)
require(grlue)
require(gridExtra)
require(ggplot2)
require(tmap)
